import HomeLink from "../../components/HomeLink/HomeLink";

export default function Credits() {
  return (
    <div>
      <HomeLink />
      <h3>Credits</h3>
      <p>
        All resources are used in accordance with their respective licenses.
      </p>
      <p>
        Created by Julius Williams. <br />
        Dedicated to Matthew Williams.
      </p>
      <p>
        The dictionaries used in this game were generated by combining and
        filtering multiple publicly available dictionaries. As a result,
        non‑existent words may occasionally appear, and some valid words may be
        rejected.
      </p>
      <br />
      <h4>Resources Used in Dictionaries</h4>
      <p>
        All of the following resources are used internally only and are not
        redistributed.
      </p>
      <ul>
        <li>
          Base dictionary generator:{" "}
          <a
            href="https://app.aspell.net/create"
            target="_blank"
            rel="noopener noreferrer"
          >
            Aspell Creator
          </a>
        </li>
        <li>
          Bad‑word dictionary/filter:{" "}
          <a
            href="https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words"
            target="_blank"
            rel="noopener noreferrer"
          >
            LDNOOBW Bad Word List
          </a>
        </li>
        <li>WordNet (Python module)</li>
      </ul>
      <br />
      <p>
        Fonts are provided by Google Fonts. <br />
        This website was built using React and Vite. <br />
        This site is currently in beta and may contain bugs.
      </p>
      <br />
      <small>
        Copyright © 2026 Julius Williams
        <br />
        All rights reserved.
        <br />
        This repository and its contents are protected by copyright law. No part
        of this repository may be copied, modified, distributed, published,
        sublicensed, or used in any form without prior written permission from
        the copyright holder.
      </small>
    </div>
  );
}
